### ISSUE TITLE
Self-Invoking func

### ISSUE THREAD

**Issue by Bodichelly** [yklym/euro-diffusion#8]
https://github.com/yklym/euro-diffusion/blob/a8bbb95205b7d54586b60b9ee9200f0b03b70afb/src/index.ts#L18
https://github.com/yklym/euro-diffusion/blob/a8bbb95205b7d54586b60b9ee9200f0b03b70afb/src/index.ts#L145

U r not exporting main() anywhere, u can make it self-Invoking

**Comment by YklymGz** [comment]
this pattern is not suitable here because the size of main function. This will only increase the indentation
